// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLZUaIyCSzWssC93aJSS0mL4HYtz18mF8',
    appId: '1:880073372925:web:67560cb5bca1786fd13a94',
    messagingSenderId: '880073372925',
    projectId: 'geofeed-1b88f',
    authDomain: 'geofeed-1b88f.firebaseapp.com',
    storageBucket: 'geofeed-1b88f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWSuoa0rbp4coAp-X7AYTHGSd7dXL0_Ww',
    appId: '1:880073372925:android:2961ff38b4c92701d13a94',
    messagingSenderId: '880073372925',
    projectId: 'geofeed-1b88f',
    storageBucket: 'geofeed-1b88f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqHsiLhvZ9UZLN58STndKsQLhkGmxT-yk',
    appId: '1:880073372925:ios:2e174d3d4e7f6a0fd13a94',
    messagingSenderId: '880073372925',
    projectId: 'geofeed-1b88f',
    storageBucket: 'geofeed-1b88f.firebasestorage.app',
    iosBundleId: 'com.example.geofeed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqHsiLhvZ9UZLN58STndKsQLhkGmxT-yk',
    appId: '1:880073372925:ios:2e174d3d4e7f6a0fd13a94',
    messagingSenderId: '880073372925',
    projectId: 'geofeed-1b88f',
    storageBucket: 'geofeed-1b88f.firebasestorage.app',
    iosBundleId: 'com.example.geofeed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLZUaIyCSzWssC93aJSS0mL4HYtz18mF8',
    appId: '1:880073372925:web:699406229f6d9b2ed13a94',
    messagingSenderId: '880073372925',
    projectId: 'geofeed-1b88f',
    authDomain: 'geofeed-1b88f.firebaseapp.com',
    storageBucket: 'geofeed-1b88f.firebasestorage.app',
  );
}
